comboRobot:
    myrobot:
      hardware_interface:
        joints:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
          
    controller:
      myrobot_state:
        type: joint_state_controller/JointStateController
        publish_rate: 200

      combo_trajectory:
        type: effort_controllers/JointTrajectoryController
        joints:
          - joint1
          - joint2
          - joint3
          - joint4
          - joint5
          - joint6
        gains:
          joint1: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          joint2: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          joint3: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          joint4: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          joint5: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
          joint6: {p: 30.0, i: 1, d: 0, i_clamp_min: -1, i_clamp_max: 1}
        velocity_ff:
          joint1: 1.0
          joint2: 1.0
          joint3: 1.0
          joint4: 1.0
          joint5: 1.0
          joint6: 1.0
        constrains:
          goal_time: 10.0
          joint1:
            goal: 0.5
          joint2:
            goal: 0.5
          joint3:
            goal: 0.5
          joint4:
            goal: 0.5
          joint5:
            goal: 0.5
          joint6:
            goal: 0.5
